title_name = "COD: Black Ops II"
title_id = "415608C3"
hash = "4B54ED67E14D0F24" # CoDMP.exe

[[patch]]
	name = "xenia fixes"
	author = "hindercanrun"
	is_enabled = true

	# exe booting
	[[patch.be32]]
		address = 0x8267F6D8
		value = 0x60000000

[[patch]]
	name = "patches"
	author = "hindercanrun"
	is_enabled = true

	# spamming stream starving print
	[[patch.be32]]
		address = 0x82793160
		value = 0x60000000

	# dvar set spam
	[[patch.be32]]
		address = 0x82629034
		value = 0x60000000

	# dvar dump
	[[patch.be32]]
		address = 0x82357E78
		value = 0x60000000

	# sound bank error
	[[patch.be32]]
		address = 0x8278A918
		value = 0x60000000

	# live_readPublisherStorageLocally
	[[patch.be32]]
		address = 0x827F29FC
		value = 0x38800001

	# nested task assert
	[[patch.be32]]
		address = 0x827EB0FC
		value = 0x60000000

	[[patch.be32]]
		address = 0x827EC73C
		value = 0x60000000

	[[patch.be32]]
		address = 0x827B09A0
		value = 0x60000000

	[[patch.be32]]
		address = 0x8295B204
		value = 0x60000000