title_name = "COD: Black Ops II"
title_id = "415608C3"
hash = "E8C4D8DE8034E862" # default_mp.xex

[[patch]]
	name = "xenia fixes"
	author = "hindercanrun"
	is_enabled = true

	# anti-piracy check
	[[patch.be32]]
		address = 0x82282444
		value = 0x60000000