title_name = "Black Ops 2"
title_id = "415608C3"
hash = "8065554A6AF089B0" # CoDMP.exe

[[patch]]
	name = "xenia fixes"
	author = "hindercanrun"
	is_enabled = true

	# exe booting
	[[patch.be32]]
		address = 0x8263CA1C
		value = 0x60000000

	# white list
	[[patch.be32]]
		address = 0x827AD990
		value = 0x60000000

	# anti piracy check
	[[patch.be32]]
		address = 0x8263C52C
		value = 0x60000000

[[patch]]
	name = "kys"
	author = "hindercanrun"
	is_enabled = true

	# stream starving print
	[[patch.be32]]
		address = 0x8274CB88
		value = 0x60000000

	# dvar set
	[[patch.be32]]
		address = 0x825E24F0
		value = 0x60000000

	# dvar dump
	[[patch.be32]]
		address = 0x8233CBD0
		value = 0x60000000

	# nested task assert
	[[patch.be32]]
		address = 0x827A0D6C
		value = 0x60000000

	[[patch.be32]]
		address = 0x825D8DA4
		value = 0x60000000

	# live_readPublisherStorageLocally
	[[patch.be8]]
		address = 0x827A9DF4
		value = 0x1

	[[patch.be32]]
		address = 0x825E3268
		value = 0x60000000